name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - dev   # Staging branch for staging environment

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Staging
      if: github.ref == 'refs/heads/dev'  # Runs only for the staging branch
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRI_KEY }}
        port: 22
        script: |
          run: echo -e "\033[1mCD into the /var/www/node-seqjob/\033[0m"
          echo "CD into the /var/www/node-seqjob/"
          cd /var/www/node-seqjob/

          echo "Pulling latest update from remote"
          git pull

          echo "Checkout to dev branch"
          git checkout dev
          
          echo "Confirming branch"
          git branch
          
          echo "Confirming latest update from remote"
          git pull
          
          echo "building app"
          npm run build
          echo "Restarting app with pm2..."
          pm2 restart 1
